-- Supabase Database Schema for onboarding-form

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. PROFILES TABLE
-- Stores primary user profile details collected during onboarding step 1.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    mobile TEXT,
    country TEXT,
    date_of_birth DATE,
    gender TEXT,
    profile_pic TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for fast profile lookups by email
CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);

-- =========================================================================
-- 2. ROLES TABLE
-- Stores specific user roles and academic metadata.
-- One-to-one relationship with profiles.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    role_name TEXT NOT NULL,
    academic_level TEXT,
    institution TEXT,
    
    -- Onboarding Status
    status TEXT DEFAULT 'pending' NOT NULL,
    
    -- Student role specific details
    grade_class TEXT,
    preferred_subjects TEXT, -- Comma-separated list of subjects
    
    -- Teacher role specific details
    teaching_experience TEXT,
    subjects_taught TEXT, -- Comma-separated list of subjects
    
    -- Parent role specific details
    child_grade TEXT,
    number_of_children INTEGER DEFAULT 1,
    learning_goals TEXT,
    
    -- Administrator role specific details
    department TEXT,
    role_title TEXT,
    access_level TEXT DEFAULT 'full',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for role lookup via profile_id
CREATE INDEX IF NOT EXISTS idx_roles_profile_id ON public.roles(profile_id);

-- =========================================================================
-- 3. PREFERENCES TABLE
-- Stores learning preferences and study configuration details.
-- One-to-one relationship with profiles.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    daily_learning_time TEXT DEFAULT '30m',
    preferred_language TEXT DEFAULT 'English',
    preferences_list TEXT, -- Comma-separated list of preferences
    custom_goals TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for preferences lookup via profile_id
CREATE INDEX IF NOT EXISTS idx_preferences_profile_id ON public.preferences(profile_id);

-- =========================================================================
-- 4. NOTIFICATIONS TABLE
-- Stores notifications and alerts channel options.
-- One-to-one relationship with profiles.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    email_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    sms_enabled BOOLEAN DEFAULT FALSE NOT NULL,
    push_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    weekly_enabled BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Index for notifications lookup via profile_id
CREATE INDEX IF NOT EXISTS idx_notifications_profile_id ON public.notifications(profile_id);

-- =========================================================================
-- 5. COUNTRIES TABLE (Reference Lookup Table)
-- Stores metadata of supported global locations.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.countries (
    name TEXT PRIMARY KEY,
    code TEXT NOT NULL,
    continent TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed initial countries
INSERT INTO public.countries (name, code, continent) VALUES
('United States', 'US', 'North America'),
('United Kingdom', 'GB', 'Europe'),
('Canada', 'CA', 'North America'),
('Germany', 'DE', 'Europe'),
('India', 'IN', 'Asia'),
('Japan', 'JP', 'Asia'),
('Australia', 'AU', 'Oceania'),
('Singapore', 'SG', 'Asia')
ON CONFLICT (name) DO UPDATE SET
    code = EXCLUDED.code,
    continent = EXCLUDED.continent;

-- =========================================================================
-- 6. SUBJECTS TABLE (Reference Table)
-- Stores list of core learning topics/subjects.
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed initial subjects
INSERT INTO public.subjects (name) VALUES
('Mathematics'),
('Science (Physics/Chemistry/Biology)'),
('English Literature'),
('Computer Science'),
('World History'),
('Art & Creative Design'),
('Business & Economics'),
('Music Theory'),
('Foreign Languages'),
('Environmental Science')
ON CONFLICT (name) DO NOTHING;

-- =========================================================================
-- 7. SCHEMA MIGRATION FOR EXISTING TABLES
-- Run this section if you already have the tables created to add new columns.
-- =========================================================================
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'pending' NOT NULL;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS grade_class TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS preferred_subjects TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS teaching_experience TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS subjects_taught TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS child_grade TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS number_of_children INTEGER DEFAULT 1;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS learning_goals TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS department TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS role_title TEXT;
ALTER TABLE public.roles ADD COLUMN IF NOT EXISTS access_level TEXT DEFAULT 'full';